In [1]:
import numpy as np

In [3]:
lst=[1,2,3,4,5]
arr=np.array(lst)
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)   

numpy.ndarray

In [5]:
arr.shape   

(5,)

In [6]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

arr1=np.array([lst1, lst2, lst3])
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [7]:
arr[3]

4

In [8]:
arr[3]=8
arr

array([1, 2, 3, 8, 5])

In [9]:
arr[-1]

5

In [10]:
arr[:-1]

array([1, 2, 3, 8])

In [11]:
arr[::-3]

array([5, 2])

In [12]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [13]:
arr1[:,1]  

array([2, 3, 4])

In [14]:
arr1[:,3:].shape  

(3, 2)

In [15]:
arr1[1:, 1:3]  

array([[3, 4],
       [4, 5]])

In [16]:
arr[arr<2]

array([1])

In [17]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [18]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [19]:
np.arange(1,20,2).reshape(2,5,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [20]:
arr*arr

array([ 1,  4,  9, 64, 25])

In [21]:
arr1*arr1

array([[ 1,  4,  9, 16, 25],
       [ 4,  9, 16, 25, 36],
       [ 9, 16, 25, 36, 49]])

In [22]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.random.randint(10,50,4).reshape(2,2)

array([[29, 24],
       [24, 38]])

In [25]:
np.random.randn(5,6)

array([[ 0.00213881, -1.19875888,  0.2956772 ,  0.51815934,  0.30564676,
         1.86093791],
       [ 1.33134359, -1.850015  ,  0.57283213,  0.52621673,  0.19058163,
        -0.47654783],
       [ 0.50355711,  1.78304754,  0.35912518,  0.27687489,  1.13301928,
        -0.44040897],
       [ 0.51087979,  0.43116438,  0.44513637,  1.91817916, -0.06861203,
        -0.06755739],
       [ 0.85423378, -0.87499768,  0.18727279,  0.67205069,  1.43485373,
        -0.47846185]])

In [26]:
np.random.random_sample((4,7))

array([[0.96691334, 0.80211747, 0.68355999, 0.90128155, 0.13945301,
        0.89079056, 0.62276011],
       [0.38213325, 0.07515402, 0.28969765, 0.75762404, 0.91076868,
        0.22963633, 0.54793286],
       [0.09145526, 0.1098273 , 0.49507067, 0.11404336, 0.32419731,
        0.61924711, 0.75506704],
       [0.44362604, 0.37930588, 0.45828641, 0.07042866, 0.90942321,
        0.46906715, 0.25297652]])

In [27]:
n1=np.array([10,20,30,40,50])
np.save('my_numpy', n1)

In [28]:
np.load('my_numpy.npy')

array([10, 20, 30, 40, 50])

In [30]:
np.full((3,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [35]:
n5=np.arange(1,20,2)
n5

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [36]:
n6=np.arange(40,60,2)
n6

array([40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [37]:
np.vstack((n5, n6))

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58]])

In [38]:
np.hstack((n5,n6))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58])

In [39]:
np.column_stack((n5,n6))

array([[ 1, 40],
       [ 3, 42],
       [ 5, 44],
       [ 7, 46],
       [ 9, 48],
       [11, 50],
       [13, 52],
       [15, 54],
       [17, 56],
       [19, 58]])

In [45]:
n1=np.array([10,20,30,40,50])
n2=np.array([40,50,60,70,80])

In [46]:
np.intersect1d(n1,n2)

array([40, 50])

In [47]:
np.setdiff1d(n1,n2)

array([10, 20, 30])

In [48]:
np.setdiff1d(n2,n1)

array([60, 70, 80])

In [51]:
np.sum([n1,n2], axis=0) #axis-0 = column

array([ 50,  70,  90, 110, 130])

In [52]:
np.sum([n1,n2], axis=1) #axis-1 = row

array([150, 300])

In [53]:
n1=np.array([10,20,30,40,50])

In [54]:
np.mean(n1)

30.0

In [55]:
np.median(n1)

30.0

In [56]:
np.std(n1)

14.142135623730951